# Generated by Django 5.1.5 on 2025-04-24 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_attraction_itinerary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerary',
            name='attractions',
        ),
        migrations.RemoveField(
            model_name='itinerary',
            name='user',
        ),
        migrations.DeleteModel(
            name='Attraction',
        ),
        migrations.DeleteModel(
            name='Itinerary',
        ),
    ]
