# Generated by Django 5.2 on 2025-04-25 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0002_itinerarydownloadlog_delete_itinerarylog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerarydownloadlog',
            name='destination',
        ),
    ]
